---
abstract: 'Test Anything interface for testing Exim4 configurations'
author:
  - 'Nigel Metheringham, C<< <nigelm at cpan.org> >>'
  - 'Nigel Metheringham <nigelm@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  FindBin: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.99'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-MTA-Exim4
no_index:
  directory:
    - inc
    - t
requires:
  Class::Accessor::Fast: 0
  FindBin: 0
  IPC::Cmd: 0
  Test::Builder: 0
  Test::More: 0
  perl: 5.6.0
resources:
  MailingList: http://lists.exim.org/mailman/listinfo/exim-dev
  license: http://dev.perl.org/licenses/
  repository: http://github.com/nigelm/Test-MTA-Exim4/
version: 0.02
