---
abstract: 'Test Anything interface for testing Exim4 configurations'
author:
  - 'Nigel Metheringham <nigelm@cpan.org>'
build_requires:
  Carp: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  FindBin: 0
  Scalar::Util: 0
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200002, CPAN::Meta::Converter version 2.110360'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-MTA-Exim4
no_index:
  directory:
    - inc
requires:
  Class::Accessor::Fast: 0
  IPC::Cmd: 0
  Test::Builder: 0
  perl: 5.006
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Test-MTA-Exim4
  homepage: http://search.cpan.org/dist/Test-MTA-Exim4
  repository: git://github.com/nigelm/Test-MTA-Exim4.git
version: 0.04
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: '@NIGELM/Git::NextVersion'
      version: 1.110330
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@NIGELM/Git::Check'
      version: 1.110330
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@NIGELM/GatherDir'
      version: 4.200002
    -
      class: Dist::Zilla::Plugin::CompileTests
      name: '@NIGELM/CompileTests'
      version: 1.103030
    -
      class: Dist::Zilla::Plugin::CriticTests
      name: '@NIGELM/CriticTests'
      version: 1.102280
    -
      class: Dist::Zilla::Plugin::MetaTests
      name: '@NIGELM/MetaTests'
      version: 4.200002
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@NIGELM/PodCoverageTests'
      version: 4.200002
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@NIGELM/PodSyntaxTests'
      version: 4.200002
    -
      class: Dist::Zilla::Plugin::PodSpellingTests
      name: '@NIGELM/PodSpellingTests'
      version: 1.103491
    -
      class: Dist::Zilla::Plugin::KwaliteeTests
      name: '@NIGELM/KwaliteeTests'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::PortabilityTests
      name: '@NIGELM/PortabilityTests'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::SynopsisTests
      name: '@NIGELM/SynopsisTests'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::MinimumVersionTests
      name: '@NIGELM/MinimumVersionTests'
      version: 1.101421
    -
      class: Dist::Zilla::Plugin::HasVersionTests
      name: '@NIGELM/HasVersionTests'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::DistManifestTests
      name: '@NIGELM/DistManifestTests'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::UnusedVarsTests
      name: '@NIGELM/UnusedVarsTests'
      version: 1.100860
    -
      class: Dist::Zilla::Plugin::EOLTests
      name: '@NIGELM/EOLTests'
      version: 0.02
    -
      class: Dist::Zilla::Plugin::InlineFiles
      name: '@NIGELM/InlineFiles'
      version: 4.200002
    -
      class: Dist::Zilla::Plugin::ReportVersions
      name: '@NIGELM/ReportVersions'
      version: 1.102460
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@NIGELM/PruneCruft'
      version: 4.200002
    -
      class: Dist::Zilla::Plugin::PruneFiles
      name: '@NIGELM/PruneFiles'
      version: 4.200002
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@NIGELM/ManifestSkip'
      version: 4.200002
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@NIGELM/AutoPrereqs'
      version: 4.200002
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@NIGELM/MetaConfig'
      version: 4.200002
    -
      class: Dist::Zilla::Plugin::MetaResources
      name: '@NIGELM/MetaResources'
      version: 4.200002
    -
      class: Dist::Zilla::Plugin::Authority
      name: '@NIGELM/Authority'
      version: 1.003
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@NIGELM/ExtraTests'
      version: 4.200002
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@NIGELM/NextRelease'
      version: 4.200002
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@NIGELM/PkgVersion'
      version: 4.200002
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: '@NIGELM/PodWeaver'
      version: 3.101641
    -
      class: Dist::Zilla::Plugin::License
      name: '@NIGELM/License'
      version: 4.200002
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@NIGELM/MakeMaker'
      version: 4.200002
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@NIGELM/MetaYAML'
      version: 4.200002
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@NIGELM/MetaJSON'
      version: 4.200002
    -
      class: Dist::Zilla::Plugin::ReadmeFromPod
      name: '@NIGELM/ReadmeFromPod'
      version: 0.14
    -
      class: Dist::Zilla::Plugin::InstallGuide
      name: '@NIGELM/InstallGuide'
      version: 1.101461
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@NIGELM/Manifest'
      version: 4.200002
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@NIGELM/Git::Commit'
      version: 1.110330
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@NIGELM/Git::Tag'
      version: 1.110330
    -
      class: Dist::Zilla::Plugin::Git::CommitBuild
      name: '@NIGELM/Git::CommitBuild'
      version: 1.110330
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@NIGELM/Git::Push'
      version: 1.110330
    -
      class: Dist::Zilla::Plugin::CheckChangeLog
      name: '@NIGELM/CheckChangeLog'
      version: 0.01
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@NIGELM/UploadToCPAN'
      version: 4.200002
    -
      class: Dist::Zilla::Plugin::AssertOS
      name: AssertOS
      version: 0.04
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.200002
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.200002
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.200002
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.200002
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.200002
x_authority: cpan:NIGELM
